### ISSUE TITLE
Components 

### ISSUE THREAD

**Issue by thabti** [quran/common-components#2]
@mmahalwy I started moving the button we use on quranicaudio over. Let me know if you have any specific components you have in mind. What would be cool in the future we we can have an Ayah Component that can render ayah's and call our api to retrieve the data.

**Comment by mmahalwy** [comment]
Yes! Those are all really good components. I can make issues and we can use the project board to move components over. How does that sound?

**Comment by thabti** [comment]
@mmahalwy awesome stuff bro - saw your commit. Inshallah tonight going to stay up and get the demo page fully working and add more components.

**Comment by thabti** [comment]
I will also setup storybook to generate the demo page.

**Comment by thabti** [comment]
@mmahalwy https://quran.github.io/common-components/

**Comment by mmahalwy** [comment]
dude, awesome! does it auto deploy?

**Comment by thabti** [comment]
@mmahalwy yep, all done via circle-ci

**Comment by mmahalwy** [comment]
sweet <3

**Comment by mmahalwy** [comment]
Oh, last thing, thoughts about circle-ci vs travis?

**Comment by thabti** [comment]
@mmahalwy I spent all night trying to get travis to play nice with pushing and updating gh-pages, but in the end I gave up. Would it be okay to stick to circle-ci for now. cc @ahmedre

**Comment by ahmedre** [comment]
sounds good to me - jazakAllah khairan Sabeur!

**Comment by mmahalwy** [comment]
sounds good to me too!
