### ISSUE TITLE
Option to close drawer 

### ISSUE THREAD

**Issue by naveed-ahmad** [quran/common-components#42]
Related: https://github.com/quran/quran.com-frontend/issues/513
Demo: http://codepen.io/arshdkhn1/pen/ZBajrE/

**Comment by ar5had** [comment]
@naveed-ahmad Where should I put the close button? Will it be fine to put a close button at the top of sidebar?

**Comment by ar5had** [comment]
and I dont think the default behaviour of sidebar should be to get closed whenever any item inside the sidebar is clicked.

**Comment by naveed-ahmad** [comment]
@arshdkhn1 

<img width="174" alt="2017-04-09_19322" src="https://cloud.githubusercontent.com/assets/701567/24838135/64a9eef6-1d5b-11e7-905b-f725ca5e76e0.png">
<img width="183" alt="2017-04-09_1932" src="https://cloud.githubusercontent.com/assets/701567/24838134/64a99352-1d5b-11e7-9629-de23253b911f.png">

**Comment by ar5had** [comment]
@naveed-ahmad ohk cool.

**Comment by naveed-ahmad** [comment]
fixed https://github.com/quran/common-components/pull/52
