### ISSUE TITLE
[BUG] Drawer close icon not working

### ISSUE THREAD

**Issue by thabti** [quran/common-components#48]
https://quran.github.io/common-components/?selectedKind=Drawer&selectedStory=default&full=0&down=1&left=1&panelRight=0&downPanel=kadirahq%2Fstorybook-addon-actions%2Factions-panel

<img width="423" alt="screen shot 2017-04-15 at 12 48 55 am" src="https://cloud.githubusercontent.com/assets/2606228/25058802/6400add2-2175-11e7-93df-98f363c7963a.png">

@arshdkhn1 I will assign this for you since you worked on it.

**Comment by ar5had** [comment]
@sabeurthabti hmm I know what's the issue. Its becoz of the `useCapture` truthy value.. Before submitting a fix, I want to clear a doubt-
Drawer closes when user clicks inside the drawer which IMO is not the correct behavior. Closing of drawer should be configurable for the clicks outside the drawer element. What do you say?

**Comment by thabti** [comment]
I totally missed this, I apologise @arshdkhn1. I think this issue is now resolved.
