### ISSUE TITLE
Drawer Component Throws Error on Body Click

### ISSUE THREAD

**Issue by mannanali413** [quran/common-components#61]
Hi,

I am running a local build of the quran.com-frontend. While working, I found the following error that
occurs on each body click.

<img width="707" alt="screen shot 2017-07-29 at 7 49 05 pm" src="https://user-images.githubusercontent.com/1666618/28745492-0639a7ec-7497-11e7-9e56-19957d5e235e.png">

In the Drawer Component, the event handler for clicks on the body tries to call 
the contains method on a Styled Component.

I have seen the API reference for Styled Components, and have not come across any ``` contains ``` method.

**Comment by mmahalwy** [comment]
Yeah, noticed that too. Hate it!

**Comment by naveed-ahmad** [comment]
@mmahalwy StyledComponent is evil :) fixed.
