### ISSUE TITLE
some errors

### ISSUE THREAD

**Issue by thabti** [quran/common-components#7]
@mmahalwy 

I am trying to make the `npm` pipe line work, however I am running in to path errors. We will have to keep everything contained. I will see what I can do about scss variables however images and such have to be contained to specific components, so we don't have to worry about paths. Unless you have any ideas.

```js
/Users/sab/workspace/apps/audio.quran.com/node_modules/loader-runner/lib/LoaderRunner.js:109
                        throw e;
                        ^

Error: Module build failed:
@import '../../styles/variables.scss';
^
      File to import not found or unreadable: ../../styles/variables.scss
Parent style sheet: stdin
````

**Comment by thabti** [comment]
let's get the drawer component merged, then we should try to solve this issue.

**Comment by thabti** [comment]
I think have a solution, we drop the `components` so we have a more flat structure which will be like our generated `lib` folder on npm.

**Comment by mmahalwy** [comment]
+1 on that.
